# --- !Ups

create table "competition" (
  "compet_id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "examiner_id" varchar not null,
  "headline" varchar not null,
  "description" varchar not null,
  "img_url" varchar not null,
  "state_tp" int not null,
  "participant_cnt" bigint not null,
  "reward" bigint not null,
  "regi_date" date not null default sysdate
);

insert into "competition" values(1, '' ,'', 'Mercari Price Suggestion Challenge', 'Can you automatically suggest product prices to online sellers?', '', 1, 2323, 3000000, sysdate);
insert into "competition" values(2, '' ,'', 'Toxic Comment Classification Challenge', 'Identify and classify toxic online comments', '', 1, 2323, 3000000, sysdate);
insert into "competition" values(3, '' ,'', 'IEEEs Signal Processing Society - Camera Model Identification', 'Identify from which camera an image was taken\n$25,000\nPrize Money', '', 1, 2323, 3000000, sysdate);

create table "competition_overview" (
  "competition_overview_id" bigint generated by default as identity(start with 1) not null primary key,
  "description" varchar not null,
  "evaluation" varchar not null,
  "prizes" varchar not null,
  "kernels_faq" varchar not null,
  "timeline" varchar not null,
  "regi_date" date not null default sysdate
);


# --- !Downs

drop table "competition" if exists;