# --- !Ups

create table "competition" (
  "compet_id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "examiner_id" varchar not null,
  "headline" varchar not null,
  "description" varchar not null,
  "img_url" varchar not null,
  "state_tp" int not null,
  "participant_cnt" bigint not null,
  "reward" bigint not null,
  "regi_date" date not null default sysdate
);

insert into "competition" values(1, '' ,'', 'Mercari Price Suggestion Challenge', 'Can you automatically suggest product prices to online sellers?', '', 1, 2323, 3000000, sysdate);
insert into "competition" values(2, '' ,'', 'Toxic Comment Classification Challenge', 'Identify and classify toxic online comments', '', 1, 2323, 3000000, sysdate);
insert into "competition" values(3, '' ,'', 'IEEEs Signal Processing Society - Camera Model Identification', 'Identify from which camera an image was taken\n$25,000\nPrize Money', '', 1, 2323, 3000000, sysdate);

create table "competition_overview" (
  "competition_overview_id" bigint generated by default as identity(start with 1) not null primary key,
  "competition_id" bigint not null,
  "description" varchar not null,
  "evaluation" varchar not null,
  "prizes" varchar not null,
  "kernels_faq" varchar not null,
  "timeline" varchar not null,
  "regi_date" date not null default sysdate
);

insert into "competition_overview" values(1, 1, 'description1' ,'evaluation1', 'prizes1', 'kernels_faq1', 'timeline1', sysdate);
insert into "competition_overview" values(2, 2, 'description2' ,'evaluation2', 'prizes2', 'kernels_faq2', 'timeline2', sysdate);
insert into "competition_overview" values(3, 3, 'description3' ,'evaluation3', 'prizes3', 'kernels_faq3', 'timeline3', sysdate);

create table "user" (
  "user_id" bigint generated by default as identity(start with 1) not null primary key,
  "login_id" varchar2 not null,
  "password" varchar2 not null,
  "regi_date" date not null default sysdate,
  "edit_date" date
);

insert into "user" values(1, 'qqq', '123456', sysdate, null);

# --- !Downs

drop table "competition" if exists;
drop table "competition_overview" if exists;
drop table "user" if exists;