# --- !Ups

create table "competition" (
  "competId" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "examinerId" varchar not null,
  "headline" varchar not null,
  "description" varchar not null,
  "imgUrl" varchar not null,
  "stateTp" int not null,
  "participantCnt" bigint not null,
  "reward" bigint not null,
  "regiDate" date not null default sysdate
);

insert into "competition" values(1, '' ,'', 'Mercari Price Suggestion Challenge', 'Can you automatically suggest product prices to online sellers?', '', 1, 2323, 3000000, sysdate);
insert into "competition" values(2, '' ,'', 'Toxic Comment Classification Challenge', 'Identify and classify toxic online comments', '', 1, 2323, 3000000, sysdate);
insert into "competition" values(3, '' ,'', 'IEEEs Signal Processing Society - Camera Model Identification', 'Identify from which camera an image was taken\n$25,000\nPrize Money', '', 1, 2323, 3000000, sysdate);

# --- !Downs

drop table "competition" if exists;