#!/bin/bash

PID_PATH=./target/universal/stage/RUNNING_PID

if test -z "$1"
then
  echo "Command not found. [start | stop]"
fi

case "$1" in
    start)
        source production;
        sbt runProd;
    ;;
    stop)
        if [ -f "$PID_PATH" ]
        then
            kill `cat $PID_PATH`
        else
            echo "$file not found."
        fi
    ;;
esac

exit 0
